#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Grava tudo num .env de produção separado (não no seu .env de desenvolvimento).
ENV_FILE=".env.prod"

TOTAL_STAGES=10

banner "Deploy do Francis — Oracle Cloud Always Free (T9)"

note "Este assistente NÃO acessa a Oracle nem a VM por você. Ele diz o que"
note "clicar, captura os valores, gera o $ENV_FILE completo (secrets inclusos)"
note "e mostra os comandos exatos para colar na VM. Referência de fundo:"
note "DEPLOY_ORACLE.md."
pause "Enter para começar"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Oracle: criar a instância Always Free"
open_url "https://cloud.oracle.com"
step "Compute -> Instances -> Create instance."
step "Image: Canonical Ubuntu 22.04 (ou 24.04)."
step "Shape: VM.Standard.A1.Flex -- 1 a 2 OCPU, 6 a 12 GB RAM (dentro do Always Free)."
note "Se der 'out of capacity': troque de Availability Domain, de regiao, ou use"
note "o shape VM.Standard.E2.1.Micro (x86, 1 GB -- sobe, mas o build fica lento)."
step "Add SSH keys: cole sua chave PUBLICA."
note "Sem chave? Rode noutro terminal:  ssh-keygen -t ed25519 -C francis-deploy"
note "e cole a saida de:  cat ~/.ssh/id_ed25519.pub"
step "Create. Espere 'Running' e copie o Public IPv4 address."
ask SERVER_IP "Cole o IPv4 publico da VM:"
if [[ ! "$SERVER_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  warn "isso nao parece um IPv4 (esperado algo como 129.159.1.2). Rode de novo."
  exit 1
fi
SITE_HOST="${SERVER_IP//./-}.sslip.io"
say "Host publico sera:  https://$SITE_HOST"
write_env SITE_HOST "$SITE_HOST"
write_env SERVER_IP "$SERVER_IP"   # usado pelos comandos ssh/scp mais adiante

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Oracle: abrir as portas 80 e 443 (DOIS lugares)"
say "A Oracle bloqueia entrada em DUAS camadas. Libere as duas."
say ""
say "2a) Security List da VCN (console):"
open_url "https://cloud.oracle.com/networking/vcns"
step "Sua VCN -> a Subnet -> Security List padrao -> Add Ingress Rules. Crie 2:"
note "   Source 0.0.0.0/0  |  TCP  |  Destination port 80"
note "   Source 0.0.0.0/0  |  TCP  |  Destination port 443"
say ""
say "2b) Firewall da instancia -- rode DENTRO da VM (SSH), depois volte aqui:"
note "   ssh ubuntu@$SERVER_IP"
note "   sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
note "   sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
note "   sudo netfilter-persistent save"
confirm "Fez as duas partes (VCN + iptables na VM)?" || { warn "faca antes de seguir -- o HTTPS nao sobe sem isso."; exit 1; }

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "E-mail para o certificado (Let's Encrypt)"
say "O Caddy usa este e-mail para avisar de expiracao/problema do certificado."
ask ACME_EMAIL "Seu e-mail:"
write_env ACME_EMAIL "$ACME_EMAIL"

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Chave da IA (Google AI Studio -- gratis, sem cartao)"
open_url "https://aistudio.google.com/apikey"
step "Create API key -> copie a chave (comeca com 'AIza...')."
ask_secret GEMINI_API_KEY "Cole a chave do AI Studio:"
write_env GEMINI_API_KEY "$GEMINI_API_KEY"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Gerar os segredos da aplicacao"
if ! command -v openssl >/dev/null 2>&1; then
  warn "openssl nao encontrado. Gere cada valor abaixo e edite $ENV_FILE:"
  note "  base64 32 bytes:  WHATSAPP_CREDENTIALS_MASTER_KEY, API_KEY_PEPPER,"
  note "                    INTERNAL_API_SECRET, DASHBOARD_SESSION_SECRET"
  note "  base64 48 bytes:  ACCESS_TOKEN_SECRET"
  note "  hex 24 bytes:     POSTGRES_PASSWORD"
  SKIPPED+=("gerar segredos (openssl ausente -- preencha $ENV_FILE a mao)")
else
  say "Gerando com openssl (aleatorios, unicos desta instalacao)..."
  write_env WHATSAPP_CREDENTIALS_MASTER_KEY "$(openssl rand -base64 32)"
  write_env API_KEY_PEPPER "$(openssl rand -base64 32)"
  write_env INTERNAL_API_SECRET "$(openssl rand -base64 32)"
  write_env DASHBOARD_SESSION_SECRET "$(openssl rand -base64 32)"
  write_env ACCESS_TOKEN_SECRET "$(openssl rand -base64 48)"
  # hex (nao base64) para a senha do Postgres: ela entra numa DATABASE_URL e
  # os caracteres + / = do base64 quebrariam a string de conexao.
  write_env POSTGRES_PASSWORD "$(openssl rand -hex 24)"
  warn "GUARDE uma copia do $ENV_FILE fora da VM. Perder"
  warn "WHATSAPP_CREDENTIALS_MASTER_KEY = reescanear QR em todas as sessoes."
fi
pause "Enter para continuar"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Valores fixos do $ENV_FILE"
say "Escrevendo as constantes de producao..."
PG_PASS="$(_existing POSTGRES_PASSWORD || echo PREENCHA)"
write_env POSTGRES_USER "francis"
write_env POSTGRES_DB "francis"
write_env POSTGRES_HOST "postgres"
write_env POSTGRES_PORT "5432"
write_env DATABASE_URL "postgresql://francis:${PG_PASS}@postgres:5432/francis?schema=public"
write_env REDIS_HOST "redis"
write_env REDIS_PORT "6379"
write_env REDIS_URL "redis://redis:6379"
write_env PORT "4000"
write_env WHATSAPP_AUTO_RESTORE "true"
write_env AI_PROVIDER "gemini"
write_env AI_GEMINI_MODEL "gemini-3.5-flash"
write_env AI_GEMINI_MAX_TOKENS "2048"
write_env AI_PROMPT_VERSION "v10"
write_env AI_HISTORY_LIMIT "20"
write_env INTERNAL_API_BASE_URL "http://api:4000"
write_env API_BASE_URL "http://api:4000"
write_env ACCESS_TOKEN_TTL_SECONDS "900"
write_env REFRESH_TOKEN_TTL_DAYS "7"
write_env TRUST_PROXY_HOPS "1"
note "AI_PROMPT_VERSION=v10 (o T9 cita 'v4'; v10 e a recomendada em .env.example --"
note "v3..v10 iteram a postura de venda sobre a base de v2). Edite se o fundador pedir v4."
pause "Enter para continuar"

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Enviar o codigo e o $ENV_FILE para a VM"
say "Na VM (SSH), prepare o Docker e traga o repositorio:"
note "   ssh ubuntu@$SERVER_IP"
note "   sudo apt update && sudo apt upgrade -y"
note "   curl -fsSL https://get.docker.com | sudo sh"
note "   sudo usermod -aG docker ubuntu     # depois: exit e entre no SSH de novo"
note "   git clone <URL-do-repositorio> Whatsapp-automatico"
say ""
say "Do SEU computador, envie o $ENV_FILE gerado como o .env da VM:"
note "   scp $ENV_FILE ubuntu@$SERVER_IP:~/Whatsapp-automatico/.env"
confirm "Codigo clonado na VM e $ENV_FILE enviado como ~/Whatsapp-automatico/.env?" || { warn "faca isso antes de seguir."; exit 1; }

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "Subir os containers na VM"
say "Na VM, dentro de ~/Whatsapp-automatico:"
note "   docker compose -f docker-compose.prod.yml -f docker-compose.caddy.yml up -d --build"
say ""
say "O servico 'migrate' aplica TODAS as migrations pendentes antes de api/worker subirem."
say "Acompanhe o Caddy pegar o certificado (leva 1-2 min na 1a vez):"
note "   docker compose -f docker-compose.prod.yml -f docker-compose.caddy.yml logs -f caddy"
note "   # espere:  certificate obtained successfully"
say ""
say "Teste:"
note "   curl -fsS https://$SITE_HOST/health/ready"
note '   # deve responder:  {"status":"ok",...}'
confirm "https://$SITE_HOST/health/ready respondeu status ok, e a landing abre no navegador?" \
  || { warn "veja 'docker compose ... logs' -- Caddy, api e migrate sao os primeiros suspeitos."; exit 1; }

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage "Monitor de uptime (UptimeRobot -- gratis)"
open_url "https://uptimerobot.com"
step "Conta gratis -> Add New Monitor."
step "Type: HTTP(s).  URL:  https://$SITE_HOST/health/ready"
step "Monitoring interval: 5 minutes.  Alert Contacts: seu e-mail."
note 'Opcional (pega o 503 degraded tambem): monitor tipo Keyword, keyword'
note '"status":"ok" , com "alert when keyword NOT exists".'
confirm "Monitor criado e apontando para /health/ready?" || SKIPPED+=("criar o monitor no UptimeRobot")

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage "Validacao real (com um WhatsApp de verdade)"
say "Checklist completo em DEPLOY_ORACLE.md sec.8. Resumo:"
say ""
say "CAMINHO PRO:"
step "register -> conectar WhatsApp real -> mandar msg de outro celular -> aparece na Dashboard."
step "Ativar o plano (dentro da VM):"
note "   docker compose -f docker-compose.prod.yml exec api \\"
note "     node apps/api/dist/scripts/setTenantPlan.js \"<tenant>\" pro --apply"
step "Mandar msg -> a IA responde. Assumir -> responder texto e midia -> chega no WhatsApp."
step "Campanha pequena -> entregue. Card no Pipeline. Analytics com dados."
say ""
say "CAMINHO GRATIS:"
step "2a conta (nasce free) -> conectar WhatsApp -> msg aparece, mas a IA NAO responde."
step "Cerebro da IA / Pipeline / Campanhas / Contatos / Analytics -> bloco 'Disponivel no Plano Pro'."
step "Numa conversa: o campo de resposta esta trocado pelo aviso de recurso pago."
step "'Conectar WhatsApp' e a lista de Conversas seguem acessiveis."
say ""
confirm "Caminho PRO validado de ponta a ponta?"    && note "Pro OK"    || SKIPPED+=("validar o caminho Pro de ponta a ponta")
confirm "Caminho GRATIS validado de ponta a ponta?" && note "Gratis OK" || SKIPPED+=("validar o caminho Gratis de ponta a ponta")

finish
note "O $ENV_FILE ficou no seu computador. Guarde uma copia num lugar seguro FORA da VM."
note "Comandos de operacao (plano, excluir tenant, atualizar, backup): DEPLOY_ORACLE.md."
